return function(Input, Output)
  local bool_spec = { { input = Input.boolean, output = Output.bool_onoff } }
  local scalar_spec = { { input = Input.scalar, output = Output.raw } }
  local string_spec = { { input = Input.string, output = Output.raw } }

  return {
    { name = "access_by_lua_block", type = "block", contexts = { "http", "server", "location", "if in location" } },
    { name = "access_by_lua_file", type = "directive", spec = string_spec, contexts = { "http", "server", "location", "if in location" } },
    { name = "access_by_lua_no_postpone", type = "directive", spec = bool_spec, contexts = { "http" } },
    { name = "access_by_lua", type = "directive", spec = string_spec, contexts = { "http", "server", "location", "if in location" } },
    { name = "balancer_by_lua_block", type = "block", contexts = { "upstream" } },
    { name = "balancer_by_lua_file", type = "directive", spec = string_spec, contexts = { "upstream" } },
    { name = "balancer_keepalive", type = "directive", spec = scalar_spec, contexts = { "upstream" } },
    { name = "body_filter_by_lua_block", type = "block", contexts = { "http", "server", "location", "if in location" } },
    { name = "body_filter_by_lua_file", type = "directive", spec = string_spec, contexts = { "http", "server", "location", "if in location" } },
    { name = "body_filter_by_lua", type = "directive", spec = string_spec, contexts = { "http", "server", "location", "if in location" } },
    { name = "content_by_lua_block", type = "block", contexts = { "location", "if in location" } },
    { name = "content_by_lua_file", type = "directive", spec = string_spec, contexts = { "location", "if in location" } },
    { name = "content_by_lua", type = "directive", spec = string_spec, contexts = { "location", "if in location" } },
    { name = "exit_worker_by_lua_block", type = "block", contexts = { "http" } },
    { name = "exit_worker_by_lua_file", type = "directive", spec = string_spec, contexts = { "http" } },
    { name = "header_filter_by_lua_block", type = "block", contexts = { "http", "server", "location", "if in location" } },
    { name = "header_filter_by_lua_file", type = "directive", spec = string_spec, contexts = { "http", "server", "location", "if in location" } },
    { name = "header_filter_by_lua", type = "directive", spec = string_spec, contexts = { "http", "server", "location", "if in location" } },
    { name = "init_by_lua_block", type = "block", contexts = { "http" } },
    { name = "init_by_lua_file", type = "directive", spec = string_spec, contexts = { "http" } },
    { name = "init_by_lua", type = "directive", spec = string_spec, contexts = { "http" } },
    { name = "init_worker_by_lua_block", type = "block", contexts = { "http" } },
    { name = "init_worker_by_lua_file", type = "directive", spec = string_spec, contexts = { "http" } },
    { name = "init_worker_by_lua", type = "directive", spec = string_spec, contexts = { "http" } },
    { name = "log_by_lua_block", type = "block", contexts = { "http", "server", "location", "if in location" } },
    { name = "log_by_lua_file", type = "directive", spec = string_spec, contexts = { "http", "server", "location", "if in location" } },
    { name = "log_by_lua", type = "directive", spec = string_spec, contexts = { "http", "server", "location", "if in location" } },
    { name = "lua_capture_error_log", type = "directive", spec = scalar_spec, contexts = { "http" } },
    { name = "lua_check_client_abort", type = "directive", spec = bool_spec, contexts = { "http", "server", "location", "if in location" } },
    { name = "lua_code_cache", type = "directive", spec = bool_spec, contexts = { "http", "server", "location", "if in location" } },
    { name = "lua_http10_buffering", type = "directive", spec = bool_spec, contexts = { "http", "server", "location", "if in location" } },
    { name = "lua_load_resty_core", type = "directive", spec = bool_spec, contexts = { "http" } },
    { name = "lua_malloc_trim", type = "directive", spec = scalar_spec, contexts = { "http" } },
    { name = "lua_max_pending_timers", type = "directive", spec = scalar_spec, contexts = { "http" } },
    { name = "lua_max_running_timers", type = "directive", spec = scalar_spec, contexts = { "http" } },
    { name = "lua_need_request_body", type = "directive", spec = bool_spec, contexts = { "http", "server", "location", "if in location" } },
    { name = "lua_package_cpath", type = "directive", spec = { { input = Input.string, output = function(v) return string.format("'%s'", v) end } }, contexts = { "http" } },
    { name = "lua_package_path", type = "directive", spec = { { input = Input.string, output = function(v) return string.format("'%s'", v) end } }, contexts = { "http" } },
    { name = "lua_regex_cache_max_entries", type = "directive", spec = scalar_spec, contexts = { "http" } },
    { name = "lua_regex_match_limit", type = "directive", spec = scalar_spec, contexts = { "http" } },
    { name = "lua_sa_restart", type = "directive", spec = bool_spec, contexts = { "http" } },
    { name = "lua_shared_dict", type = "directive", cardinality = "multiple", spec = { { input = Input.fields({ name = Input.required(Input.string), size = Input.required(Input.scalar) }), output = Output.concat(" ", { Output.field("name"), Output.field("size") }) } }, contexts = { "http" } },
    { name = "lua_socket_buffer_size", type = "directive", spec = scalar_spec, contexts = { "http", "server", "location" } },
    { name = "lua_socket_connect_timeout", type = "directive", spec = scalar_spec, contexts = { "http", "server", "location" } },
    { name = "lua_socket_keepalive_timeout", type = "directive", spec = scalar_spec, contexts = { "http", "server", "location" } },
    { name = "lua_socket_log_errors", type = "directive", spec = bool_spec, contexts = { "http", "server", "location" } },
    { name = "lua_socket_pool_size", type = "directive", spec = scalar_spec, contexts = { "http", "server", "location" } },
    { name = "lua_socket_read_timeout", type = "directive", spec = scalar_spec, contexts = { "http", "server", "location" } },
    { name = "lua_socket_send_lowat", type = "directive", spec = scalar_spec, contexts = { "http", "server", "location" } },
    { name = "lua_socket_send_timeout", type = "directive", spec = scalar_spec, contexts = { "http", "server", "location" } },
    { name = "lua_ssl_certificate_key", type = "directive", spec = string_spec, contexts = { "http", "server", "location" } },
    { name = "lua_ssl_certificate", type = "directive", spec = string_spec, contexts = { "http", "server", "location" } },
    { name = "lua_ssl_ciphers", type = "directive", spec = string_spec, contexts = { "http", "server", "location" } },
    { name = "lua_ssl_conf_command", type = "directive", cardinality = "multiple", spec = string_spec, contexts = { "http", "server", "location" } },
    { name = "lua_ssl_crl", type = "directive", spec = string_spec, contexts = { "http", "server", "location" } },
    { name = "lua_ssl_key_log", type = "directive", spec = string_spec, contexts = { "http", "server", "location" } },
    { name = "lua_ssl_protocols", type = "directive", spec = { { input = Input.string, output = Output.raw }, { input = Input.array(Input.string), output = Output.space } }, contexts = { "http", "server", "location" } },
    { name = "lua_ssl_trusted_certificate", type = "directive", spec = string_spec, contexts = { "http", "server", "location" } },
    { name = "lua_ssl_verify_depth", type = "directive", spec = scalar_spec, contexts = { "http", "server", "location" } },
    { name = "lua_thread_cache_max_entries", type = "directive", spec = scalar_spec, contexts = { "http" } },
    { name = "lua_transform_underscores_in_response_headers", type = "directive", spec = bool_spec, contexts = { "http", "server", "location", "if in location" } },
    { name = "lua_upstream_skip_openssl_default_verify", type = "directive", spec = bool_spec, contexts = { "location", "if in location" } },
    { name = "lua_use_default_type", type = "directive", spec = bool_spec, contexts = { "http", "server", "location", "if in location" } },
    { name = "lua_worker_thread_vm_pool_size", type = "directive", spec = scalar_spec, contexts = { "http" } },
    { name = "proxy_ssl_verify_by_lua_block", type = "block", contexts = { "location" } },
    { name = "proxy_ssl_verify_by_lua_file", type = "directive", spec = string_spec, contexts = { "location" } },
    { name = "rewrite_by_lua_block", type = "block", contexts = { "http", "server", "location", "if in location" } },
    { name = "rewrite_by_lua_file", type = "directive", spec = string_spec, contexts = { "http", "server", "location", "if in location" } },
    { name = "rewrite_by_lua_no_postpone", type = "directive", spec = bool_spec, contexts = { "http" } },
    { name = "rewrite_by_lua", type = "directive", spec = string_spec, contexts = { "http", "server", "location", "if in location" } },
    { name = "server_rewrite_by_lua_block", type = "block", contexts = { "http", "server" } },
    { name = "server_rewrite_by_lua_file", type = "directive", spec = string_spec, contexts = { "http", "server" } },
    { name = "set_by_lua_block", type = "block", cardinality = "multiple", arg_fields = { "res" }, args = { { input = Input.fields({ res = Input.required(Input.string) }), output = Output.field("res") } }, text_field = "script", contexts = { "server", "if in server", "location", "if in location" } },
    { name = "set_by_lua_file", type = "directive", cardinality = "multiple", spec = { { input = Input.fields({ res = Input.required(Input.string), file = Input.required(Input.string), args = Input.optional(Input.array(Input.string)) }), output = Output.concat(" ", { Output.field("res"), Output.field("file"), Output.chain(Output.field("args"), Output.space) }) } }, contexts = { "server", "if in server", "location", "if in location" } },
    { name = "set_by_lua", type = "directive", cardinality = "multiple", spec = { { input = Input.fields({ res = Input.required(Input.string), script = Input.required(Input.string), args = Input.optional(Input.array(Input.string)) }), output = Output.concat(" ", { Output.field("res"), Output.field("script"), Output.chain(Output.field("args"), Output.space) }) } }, contexts = { "server", "if in server", "location", "if in location" } },
    { name = "ssl_certificate_by_lua_block", type = "block", contexts = { "server" } },
    { name = "ssl_certificate_by_lua_file", type = "directive", spec = string_spec, contexts = { "server" } },
    { name = "ssl_client_hello_by_lua_block", type = "block", contexts = { "http", "server" } },
    { name = "ssl_client_hello_by_lua_file", type = "directive", spec = string_spec, contexts = { "http", "server" } },
    { name = "ssl_session_fetch_by_lua_block", type = "block", contexts = { "http" } },
    { name = "ssl_session_fetch_by_lua_file", type = "directive", spec = string_spec, contexts = { "http" } },
    { name = "ssl_session_store_by_lua_block", type = "block", contexts = { "http" } },
    { name = "ssl_session_store_by_lua_file", type = "directive", spec = string_spec, contexts = { "http" } },
  }
end
